version: "3.8"
services: 
    rabbitmq:
        image: rabbitmq:3.9.1-management-alpine
        hostname: diego
        container_name: rabbit_mq
        ports: 
            - 5672:5672
            - 15672:15672
        volumes:
            - ./rabbitmq/data/:/var/lib/rabbitmq/
            - ./rabbitmq/log/:/var/log/rabbitmq
        networks: 
            - messages_network

networks: 
    messages_network:
        driver: bridge